{% set version = "2.54.0.dev0" %}
{% set commit = "73fd77805fc6406f31c36212846d9e2541d19321" %}

package:
  name: git
  version: {{ version }}

source:
  - url: https://github.com/git/git/archive/{{ commit }}.tar.gz
    folder: code
    sha256: 9253a2d90886b56f68f8686a9b0d1b8ebca9d9f5d1d6166d71d7f9bb8f4abde8
    patches:
      - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - perl 5.*  # [unix]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - autoconf
    - make
    - tk
    - gettext-tools
  host:
    - libintl-devel  # [osx]
    - libcurl
    - expat
    - libiconv
    - openssl
    - pcre2
    - perl 5.*
    - zlib
  run:
    # Without the explicit dependency on curl, it seems
    # that linux_64 fails on the symbol lookup for curl_global_sslset
    - perl 5.*

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git
    - test -f $PREFIX/bin/gitk
    - test -f $PREFIX/bin/git-credential-osxkeychain  # [osx]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # Git credential commands
    - git-credential-osxkeychain 2>&1 | grep -q usage  # [osx]

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git

about:
  home: https://git-scm.com/
  license: GPL-2.0-or-later and LGPL-2.1-or-later
  license_file: code/COPYING
  summary: distributed version control system (dev build)

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
    - djsutherland
    - ytausch
